stages:
  - sync

sync_to_github:
  stage: sync
  script:
    - git config --global user.name "GitLab Sync Bot"
    - git config --global user.email "sync-bot@example.com"
    - git remote add github https://github.com/atc93/shinepy.git 
    - git push github HEAD:main
  only:
    - main
